feat(*): update doc as part of mono-repo refactor
accordproject/concerto-docs pull request #2
Opened 2023-02-21 12:38 UTC by Jonathan-Casey

### Changes

- <ONE> Change of documented repository structure in `/docs/contributing.md`

2023-03-05 15:32 UTC, dselman requested changes

2023-03-05 15:32 UTC, dselman commented on docs/contributing.md
> +* [concerto-metamodel](https://github.com/accordproject/concerto-metamodel) : contains utility functions for accessing and manipulating the new Concerto metamodel
Please remove 'new'

2023-05-03 09:38 UTC, Jonathan-Casey commented
@dselman this is ready

2023-05-03 11:22 UTC, dselman approved these changes

2023-05-03 11:22 UTC, merged