feat(*): Map Declaration Docs
accordproject/concerto-docs pull request #22
Opened 2023-10-03 09:58 UTC by Jonathan-Casey

### Description
Adds initital documentation for Map type
### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`

2024-04-30 20:15 UTC, DianaLease approved these changes
LGTM

2024-05-01 05:32 UTC, mttrbrts requested changes

2024-05-01 05:32 UTC, mttrbrts commented on docs/design/specification/model-maps.md
> +    o <required Concerto type>
Indicate that this is a key value

2024-05-01 05:32 UTC, mttrbrts commented on docs/design/specification/model-maps.md
> +## Supported Keys
Supported key types

2024-05-01 05:32 UTC, mttrbrts commented on docs/design/specification/model-maps.md
> +
Add a comment about how you turn on this feature

2024-05-08 16:20 UTC, mttrbrts commented on docs/design/specification/model-maps.md
> +}
```suggestion
map Timeline {
  o DateTime
  o Activity
}
```

2024-05-08 16:22 UTC, mttrbrts commented on docs/design/specification/model-maps.md
> +}
```suggestion
import com.my.cool@1.0.0.Activity

map Timeline {
  o DateTime
  o Activity
}
```

2024-05-09 15:02 UTC, merged